//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Attendance")
export class AttendanceEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Id: string;

@Column({nullable: true})
Date: string;

@Column({nullable: true})
Studentid: string;

@Column({nullable: true})
Activityid: string;


}
