//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Children")
export class ChildrenEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Childid: string;

@Column({nullable: true})
Name: string;

@Column({nullable: true})
Id: string;


}
