//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Lessons")
export class LessonsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Lessonid: string;

@Column({nullable: true})
Topic: string;

@Column({nullable: true})
Costperlesson: string;

@Column({nullable: true})
Id: string;


}
