//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Student")
export class StudentEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Studentid: string;

@Column({nullable: true})
Name: string;

@Column({nullable: true})
Surname: string;

@Column({nullable: true})
Id: string;


}
